shipyard:
    image: shipyard/shipyard
    ports:
        - "21080:8080"
    links:
        - rethinkdb:rethinkdb

rethinkdb:
    image: shipyard/rethinkdb
    expose:
        - "8080"
        - "28015"
        - "29015"

